### ISSUE TITLE
Block with title as constructor breaks litpro

### ISSUE THREAD

**Issue by cjloong** [jostylr/litpro-commonmark#1]
When I use a header name # Constructor and when I include it using _"Constructor" litpro breaks with error message. It works when I rename "Constructor" to something else.

Input

```

# Source Codes
- [engine1.js](#Engine "save:")


# Engine
TODO: To code engine in requirejs format for module. It should use public/private and defaults
```

```
(function() {
    Evo = Evo || {};
    Evo.Csp = Evo.Csp || {};

    _"Constructor"
})();
```

```


## Constructor
Constructor of the object accepts the csp structure and options.

```

... constructor code

```


```

Output

```

C:\Users\chekjen\git\evo\public\evo\csp>litpro -b . csp.litpro.md
error TypeError: undefined is not a function

event "text ready:csp.litpro.md:engine⫶1"
handler ``
data `Object`
context {}
scopes {}
error Error: TypeError: undefined is not a function

event "text ready:csp.litpro.md:engine⫶1"
handler [``,``]
data `Object`
context {}
scopes {}
Markdown parsing error. Last heading seen: constructor
STILL WAITING: ./

---
NOT SAVED: engine1.js AS REQUESTED BY: csp.litpro.md NEED: engine
NEED VAR: engine FROM: csp.litpro.md
PROBLEM WITH: _"Constructor" IN: engine FIlE: csp.litpro.md

```

**Comment by jostylr** [comment]
I did find an error. It is a different error than the error you reported, but it is definitely a problem. It looks like it is pulling in items up from the prototype chain. I have found one place where it is doing this and fixed it, but I am now trying to search for other places.

**Comment by cjloong** [comment]
I did find another error when I have javascript string concat having the form "_" + variable... ie. if my code have stuffs like the following code:

```
        var a = d + "_" + a;
```

Gives me error

```
C:\Users\chekjen\git\evo\public\evo\csp>litpro -b . csp.litpro.md
STILL WAITING: ./
---
NOT SAVED: engine.js AS REQUESTED BY: csp.litpro.md NEED: engine


```

Removing the above string concat code will be ok. I think its because of the underscore used because when I change the character to something else, the error dissapears.

**Comment by jostylr** [comment]
Yes. That's less an error and more an unfortunate consequence of the `_"..."` convention. It doesn't see the quote in front. You can escape underscores. So if you try `"\_"` it should give you `"_"` in your compiled code.

**Comment by cjloong** [comment]
I see. Thanks.

**Comment by jostylr** [comment]
The most recent litpro version (0.8.6) should fix the constructor issue.
